#!/usr/bin/env python3
"""
Bosly Gov v4 - Prompt Compactor
Python 3.12+
"""

from __future__ import annotations

import re
from difflib import SequenceMatcher
from typing import Any


def _normalize_text(s: str) -> str:
    s = (s or "").strip().lower()
    s = re.sub(r"\s+", " ", s)
    return s


def _extract_msg_text(m: dict[str, Any]) -> str:
    return str(m.get("message") or m.get("content") or m.get("text") or "").strip()


def deduplicate_turns(messages: list[dict]) -> list[dict]:
    """
    Remove near-identical consecutive turns (same role + high text similarity).
    Keeps first occurrence in a duplicate run.
    """
    if not messages:
        return []

    out: list[dict] = []
    prev_role = None
    prev_norm = ""
    for m in messages:
        if not isinstance(m, dict):
            continue
        role = str(m.get("role", "")).strip().lower()
        txt = _extract_msg_text(m)
        norm = _normalize_text(txt)

        if out and role == prev_role and norm and prev_norm:
            sim = SequenceMatcher(None, norm, prev_norm).ratio()
            if sim >= 0.96:
                continue

        out.append(m)
        prev_role = role
        prev_norm = norm
    return out


def strip_boilerplate(text: str) -> str:
    """
    Remove predictable low-value boilerplate from context chunks.
    """
    t = (text or "").replace("\r\n", "\n").replace("\r", "\n")

    drop_line_patterns = [
        r"^\s*this file was (generated|auto-generated).*$",
        r"^\s*do not edit this file.*$",
        r"^\s*copyright .* reserved.*$",
        r"^\s*licensed under .*?$",
        r"^\s*all rights reserved.*$",
        r"^\s*use strict;?\s*$",
    ]
    drops = [re.compile(p, re.IGNORECASE) for p in drop_line_patterns]

    kept: list[str] = []
    for ln in t.split("\n"):
        if any(rx.match(ln.strip()) for rx in drops):
            continue
        kept.append(ln)

    t = "\n".join(kept)
    t = re.sub(r"\n{3,}", "\n\n", t).strip()
    return t


def compact_text(text: str, max_tokens: int, model: str) -> str:
    """
    Compact verbose prose into short bullet facts using deterministic heuristics.
    (No LLM call.) max_tokens is approximate target.
    """
    if not text:
        return ""

    t = strip_boilerplate(text)

    chunks = re.split(r"(?<=[\.\!\?])\s+|\n+", t)
    chunks = [c.strip() for c in chunks if c and c.strip()]

    seen: set[str] = set()
    facts: list[str] = []
    for c in chunks:
        norm = _normalize_text(c)
        if len(norm) < 20:
            continue
        if norm in seen:
            continue
        seen.add(norm)

        score = 0
        if re.search(r"\b(error|failed|timeout|fix|bug|deploy|report|memory|context|token)\b", norm):
            score += 2
        if re.search(r"[A-Za-z0-9_/.-]+\.(ts|tsx|js|jsx|py|json|md|yml|yaml|css|html)", c):
            score += 2
        if re.search(r"\b(api|route|handler|function|class|module|endpoint)\b", norm):
            score += 1

        if score > 0 or len(c) <= 220:
            facts.append(c)

    bullets = [f"- {f}" for f in facts]
    if not bullets:
        bullets = [f"- {x}" for x in chunks[:10]]

    max_chars = max(80, int(max_tokens * 4))
    out_lines: list[str] = []
    used = 0
    for b in bullets:
        n = len(b) + 1
        if used + n > max_chars:
            break
        out_lines.append(b)
        used += n

    if not out_lines:
        out_lines = [f"- {t[:max_chars].strip()}"]

    return "\n".join(out_lines).strip()


def relevance_rank(snippets: list[dict], query: str) -> list[dict]:
    """
    Rank snippet dicts by lexical relevance to query.
    Expected snippet keys: path, snippet, reason, start_line, end_line
    """
    q = _normalize_text(query)
    q_terms = set(re.findall(r"[a-z0-9_]{2,}", q))

    ranked: list[tuple[float, dict]] = []
    for sn in snippets or []:
        if not isinstance(sn, dict):
            continue
        path = _normalize_text(str(sn.get("path", "")))
        body = _normalize_text(str(sn.get("snippet", "")))
        reason = _normalize_text(str(sn.get("reason", "")))
        hay_terms = set(re.findall(r"[a-z0-9_]{2,}", f"{path} {body} {reason}"))

        overlap = len(q_terms & hay_terms)
        path_bonus = 2 if any(t in path for t in q_terms if len(t) > 2) else 0
        exact_phrase = 2 if q and q in body else 0
        score = float(overlap + path_bonus + exact_phrase)

        ranked.append((score, sn))

    ranked.sort(key=lambda x: x[0], reverse=True)
    return [sn for _, sn in ranked]
